linters:
  LineLength:
    max: 120
    exclude:
      - "app/views/errors/**/*.slim"
  FileLength:
    enabled: false
  RuboCop:
    ignored_cops:
      # Default.
      - Layout/ArgumentAlignment
      - Layout/ArrayAlignment
      - Layout/BlockAlignment
      - Layout/EmptyLineAfterGuardClause
      - Layout/EndAlignment
      - Layout/FirstArrayElementIndentation
      - Layout/FirstParameterIndentation
      - Layout/HashAlignment
      - Layout/IndentationConsistency
      - Layout/IndentationWidth
      - Layout/InitialIndentation
      - Layout/LineLength
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/ParameterAlignment
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Naming/FileName
      - Style/FrozenStringLiteralComment
      - Style/IdenticalConditionalBranches
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier
      # Added manually.
      - Style/StringLiterals
      - Rails/HelperInstanceVariable
      - Style/RedundantParentheses
      - Layout/FirstArgumentIndentation
      - Layout/FirstHashElementIndentation
      - Style/TrailingCommaInHashLiteral
      - Style/TrailingCommaInArguments
      - Style/RedundantInterpolation
      - Style/TernaryParentheses
      - Layout/LineEndStringConcatenationIndentation
      - Style/MethodCallWithArgsParentheses
      - Style/RedundantLineContinuation
