default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: 5
      polling_interval: 2

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
