name: "deploy"

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [master]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Dokku
        run: |
          ls -lha
          git push --force ssh://dokku@alpha.toughbyte.com:22/ats $GITHUB_SHA:refs/heads/master
