name: Production deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [master]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: true
        default: master
      commit:
        description: "Commit to deploy, e.g. HEAD^"

jobs:
  deploy:
    if: $GITHUB_EVENT_NAME == 'workflow_dispatch' || ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Rollback
        if: "${{ github.event.inputs.commit != '' }}"
        run: git checkout ${{ github.event.inputs.commit }}
      # dokku/github-action can't find git repo when self-hosted
      - name: Push to Dokku
        run: |
          mkdir -p /root/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' >/root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          chmod 700 /root/.ssh
          ssh-keyscan -t rsa ${{ vars.DOKKU_HOST }} >> /root/.ssh/known_hosts
          git push --force ssh://dokku@${{ vars.DOKKU_HOST }}:22/${{ github.event.repository.name }} HEAD:master
