name: "deploy"

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [master]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: dokku/ci-docker-image:0.11.0
          options: -v ${{ github.workspace }}:/github/workspace
          run: |
            ls /github/workspace -lha
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@alpha.toughbyte.com:22/ats"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          git_push_flags: --force
